########################
# Install pypy and pip #
########################

- name: Check if pypy is installed
  raw: stat $HOME/pypy
  register: need_pypy
  ignore_errors: True

- name: Run get-pypy.sh
  script: get-pypy.sh
  when: need_pypy | failed

- name: Check if pip is installed
  shell: "{{ansible_python_interpreter}} -m pip --version"
  register: need_pip
  ignore_errors: True
  changed_when: false

- name: Copy get-pip.py
  copy: src=get-pip.py dest=~/get-pip.py
  when: need_pip | failed

- name: Install pip
  shell: "{{ansible_python_interpreter}} ~/get-pip.py"
  when: need_pip | failed

- name: Remove get-pip.py
  file: path=~/get-pip.py state=absent
  when: need_pip | failed

- name: Install pip launcher
  copy: src=pip dest=~/bin/pip mode=0755
  when: need_pip | failed
