apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tds-ingress
  namespace: tds-cloud
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/use-port-in-redirects: "true"
    kubernetes.io/ingress.class: "tds"
spec:
  tls:
  - hosts:
    - nginx1.tectusdreamlab.com
    secretName: nginx-ingress-tls-secret
  - hosts:
    - nginx2.tectusdreamlab.com
    secretName: nginx-ingress-tls-secret
  rules:
  - host: nginx1.tectusdreamlab.com
    http:
      paths:
      - backend:
          serviceName: nginx1
          servicePort: 80
  - host: nginx2.tectusdreamlab.com
    http:
      paths:
      - backend:
          serviceName: nginx2
          servicePort: 80