########################################
# Bootstrap kubernetes using bootkube  #
########################################

- name: Make sure the bootkube directory exists
  run_once: true
  file:
    path: "{{ bootkube_directory }}/{{ item }}"
    state: directory
  with_items:
    - assets/tls
    - assets/manifests
    - assets/auth
    - assets/bootstrap-manifests

- name: Repalce the kubeconfig file
  run_once: true
  copy:
    remote_src: true
    src: "/etc/kubernetes/kubeconfig"
    dest: "{{ bootkube_directory }}/assets/auth/kubeconfig"

- name: Copy over the certs and keys
  run_once: true
  copy:
    src: "./{{ item }}"
    dest: "{{ bootkube_directory }}/assets/{{ item }}"
  with_items:
    - tls/apiserver.crt
    - tls/apiserver.key
    - tls/service-account.key
    - tls/service-account.pub

- name: Copy over the certs and keys from remote
  run_once: true
  copy:
    remote_src: true
    src: "{{ item.0 }}"
    dest: "{{ bootkube_directory }}/assets/tls/{{ item.1 }}"
  with_together:
    - ["/etc/ssl/etcd/ca.crt","/etc/ssl/etcd/etcd-client.key","/etc/ssl/etcd/etcd-client.crt","/etc/kubernetes/ca.crt","/etc/kubernetes/ca.key"]
    - ["etcd-client-ca.crt","etcd-client.key","etcd-client.crt","ca.crt","ca.key"]

- name: Generate kubelet.key and kubelet.crt
  run_once: true
  shell: "grep '{{ item.0 }}' /etc/kubernetes/kubeconfig | awk '{print $2}' | base64 -d > {{ bootkube_directory }}/assets/tls/{{ item.1 }}"
  with_together:
    - ["client-key-data", "client-certificate-data"]
    - ["kubelet.key", "kubelet.crt"]

- name: Copy bootstrap-manifests
  run_once: true
  template:
    src: "./bootstrap-manifests/{{ item }}.j2"
    dest: "{{ bootkube_directory }}/assets/bootstrap-manifests/{{ item }}"
  with_items:
    - bootstrap-apiserver.yaml
    - bootstrap-controller-manager.yaml
    - bootstrap-scheduler.yaml

- name: Copy manifests
  run_once: true
  template:
    src: "./manifests/{{ item }}.j2"
    dest: "{{ bootkube_directory }}/assets/manifests/{{ item }}"
  with_items:
    - kube-apiserver-secret.yaml
    - kube-apiserver.yaml
    - kube-controller-manager-disruption.yaml
    - kube-controller-manager-secret.yaml
    - kube-controller-manager.yaml
    - kube-dns.yaml
    - kube-flannel.yaml
    - kube-proxy.yaml
    - kube-scheduler-disruption.yaml
    - kube-scheduler.yaml
    - kube-system-rbac-role-binding.yaml
    - pod-checkpointer.yaml
    - heapster.yaml
    - kube-dashboard.yaml
    - namespace.yaml
    - default-backend.yaml
    - ingress-controller.yaml

- name: Copy over the bootkube.sh
  run_once: true
  template:
    src: bootkube.sh.j2
    dest: "{{ bootkube_directory }}/bootkube.sh"
    mode: u+x

- name: Create the bootkube service
  run_once: true
  copy:
    src: bootkube.service
    dest: /etc/systemd/system/bootkube.service

- name: Enable and start bootkube service
  run_once: true
  systemd:
    no_block: yes
    name: bootkube
    state: started
    daemon_reload: yes

- name: Download the kubectl command line tool
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl
    dest: ./kubectl
    mode: "u+x"
