####################################
# ANSIBLE PREREQUISITES FOR COREOS #
####################################

- name: coreos-pypy
  hosts: all
  gather_facts: False
  roles:
    - pypy

################################
# Install etcd on master nodes #
################################

- name: etcd
  hosts: role=master
  become: true
  gather_facts: True
  roles:
    - etcd

################################
# Install kubelet on all nodes #
################################

- name: kubelet
  hosts: all
  become: true
  gather_facts: True
  roles:
    - kubelet

################################
# Bootstrap kubernetes cluster #
################################

- name: bootkube
  hosts: master03
  become: true
  gather_facts: True
  roles:
    - bootkube