####################################
# ANSIBLE PREREQUISITES FOR COREOS #
####################################

- name: coreos-pypy
  hosts: all
  gather_facts: False
  roles:
    - pypy


#####################################
# Install master components cluster #
#####################################

- name: master
  hosts: role=master
  become: true
  gather_facts: True
  roles:
    - etcd


#####################################
# Install node components cluster #
#####################################

- name: all
  hosts: all
  become: true
  gather_facts: True
  roles:
    - kubelet