####################################
# ANSIBLE PREREQUISITES FOR COREOS #
####################################

- name: coreos-pypy
  hosts: all
  gather_facts: False
  roles:
    - pypy


########################
# Install etcd cluster #
########################

- name: etcd
  hosts: role=master
  become: true
  gather_facts: True
  roles:
    - etcd